// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfOzMY_xza7U3n3nS42lnPNKP05EdOjvM',
    appId: '1:202387077751:web:fe217c55467597acb5a472',
    messagingSenderId: '202387077751',
    projectId: 'ming-o',
    authDomain: 'ming-o.firebaseapp.com',
    storageBucket: 'ming-o.appspot.com',
    measurementId: 'G-L91YW4WELY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJLKaNpQ5no0pM_wnQtFv0TjVdRS58mc',
    appId: '1:202387077751:android:a1397bd78bceadc4b5a472',
    messagingSenderId: '202387077751',
    projectId: 'ming-o',
    storageBucket: 'ming-o.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52EuDs6pPHEfP4u5x4eIVPiMUmnjqvOo',
    appId: '1:202387077751:ios:d102aaaa6e7e5eddb5a472',
    messagingSenderId: '202387077751',
    projectId: 'ming-o',
    storageBucket: 'ming-o.appspot.com',
    iosClientId: '202387077751-vp9r2bck4r2lodq22or0kvk7o1bb1q4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB52EuDs6pPHEfP4u5x4eIVPiMUmnjqvOo',
    appId: '1:202387077751:ios:d102aaaa6e7e5eddb5a472',
    messagingSenderId: '202387077751',
    projectId: 'ming-o',
    storageBucket: 'ming-o.appspot.com',
    iosClientId: '202387077751-vp9r2bck4r2lodq22or0kvk7o1bb1q4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingoApplication',
  );
}
